services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
