spring.application.name: spring-batch
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql:postgres
    username: postgres
    password: postgres

# https://jdbc.postgresql.org/documentation/use/
#jdbc:postgresql:database
#jdbc:postgresql:/
#jdbc:postgresql://host/database
#jdbc:postgresql://host/
#jdbc:postgresql://host:port/database
#jdbc:postgresql://host:port/